version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./mysql/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - rede-app

  php1:
    build: ./php
    container_name: php1
    restart: always
    depends_on:
      - db
    networks:
      - rede-app

  php2:
    build: ./php
    container_name: php2
    restart: always
    depends_on:
      - db
    networks:
      - rede-app

  php3:
    build: ./php
    container_name: php3
    restart: always
    depends_on:
      - db
    networks:
      - rede-app

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "4500:4500"
    depends_on:
      - php1
      - php2
      - php3
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge
